# Generated by Django 4.2.3 on 2023-07-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bechallenge_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
